### ISSUE TITLE
Angular v13 Sass issue (SassError: Can't find stylesheet to import)

### ISSUE THREAD

**Issue by alexis-landrieu-avanade** [kuhnroyal/mat-datetimepicker#216]
Hello, I have recently updated **@mat-datetimepicker/core** to **v9.0.2** and I'm getting following error from sass-loader (_Note: The build is working with v7.0.1_).

**Error**
```javascript
./src/styles.scss.webpack[javascript/auto]!=!./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[6].rules[0].oneOf[0].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[6].rules[0].oneOf[0].use[2]!./node_modules/resolve-url-loader/index.js??ruleSet[1].rules[6].rules[1].use[0]!./node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[6].rules[1].use[1]!./src/styles.scss - Error: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
6 │ @import "~@mat-datetimepicker/core/datetimepicker/datetimepicker-theme.scss";
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  src/theme/_angular.scss 6:9  @import
  src/theme/_main.scss 1:9     @import
  src/styles.scss 1:9          root stylesheet

./src/styles.scss - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
```

**Version**

```javascript
     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 13.1.2
Node: 12.22.1
Package Manager: npm 6.14.12
OS: win32 x64

Angular: 13.1.1
... animations, cdk, common, compiler, compiler-cli, core, forms
... localize, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------       
@angular-devkit/architect       0.1301.2
@angular-devkit/build-angular   13.1.2
@angular-devkit/core            13.1.2
@angular-devkit/schematics      13.1.2
@angular/cli                    13.1.2
@angular/flex-layout            13.0.0-beta.36
@schematics/angular             13.1.2
rxjs                            7.5.1
typescript                      4.5.4
```

I don't know what is causing this issue, you will find below my styles.scss:

```sass
@use '@angular/material' as mat;

@import "~@mat-datetimepicker/core/datetimepicker/datetimepicker-theme.scss";

@include mat.core();

@include mat-datetimepicker-theme($app-light-theme);
@include mat.all-component-themes($app-light-theme);
```

**Comment by bbortt** [comment]
the problem sounds like a `sass-loader` (respecitvely Angular) migration error to me.. because the style-sheet clearly exists:

```shell
$ cat package.json | grep @mat-datetimepicker
    "@mat-datetimepicker/core": "^9.0.21",

$ ls -alh node_modules/\@mat-datetimepicker/core/datetimepicker/ | grep datetimepicker-theme.scss
-rw-r--r-- 1 bbortt bbortt 1.4K Oct 26  1985 datetimepicker-theme.scss
```

there's multiple changes involved here.. and multiple fixes possible. e.g. removing the leading `~`, using `@use` instead (`@import` has been deprecated) or even adding the `stylePreprocessorOptions` to `angular.json`. please lookup the individual solutions to find out what works best for you!

I do take from this issue, that our documentation is not up to date. I'll have that fixed in the meantime.

**Comment by alexis-landrieu-avanade** [comment]
@bbortt unfortunately none of these solutions seems to be working. You will find below a repo with clean Angular project to see [the issue](https://github.com/alexis-landrieu-avanade/mat-datetimepicker-sass-loader-issue-216/runs/4727957799?check_suite_focus=true).

* https://github.com/alexis-landrieu-avanade/mat-datetimepicker-sass-loader-issue-216

**Possible related topic**

* [ng-packagr - docs: add details about exporting styles for APF 13](https://github.com/ng-packagr/ng-packagr/commit/044b47ae15fa91fcc658e33e74b28f6d4baf2022#diff-4767d2b0afa2693fb261682f07761a316d54694656ea53c2298b883ee1130913)

**Comment by bbortt** [comment]
thanks very much for the sample! I'll have a look at it..

**Comment by bbortt** [comment]
@alexis-landrieu-avanade the following works for me, even with your example..
```shell
$ git diff
diff --git a/angular.json b/angular.json
index 87247ee..547a091 100644
--- a/angular.json
+++ b/angular.json
@@ -34,6 +34,11 @@
               "./node_modules/@angular/material/prebuilt-themes/indigo-pink.css",
               "src/styles.scss"
             ],
+            "stylePreprocessorOptions": {
+              "includePaths": [
+                "node_modules"
+              ]
+            },
             "scripts": []
           },
           "configurations": {
diff --git a/src/styles.scss b/src/styles.scss
index 275fdf7..ab5fd42 100644
--- a/src/styles.scss
+++ b/src/styles.scss
@@ -2,7 +2,7 @@
 @use '@angular/material' as mat;

-// @use '@mat-datetimepicker/core/datetimepicker/datetimepicker-theme' as mat2;
-@import '~@mat-datetimepicker/core/datetimepicker/datetimepicker-theme.scss';
+@use '@mat-datetimepicker/core/datetimepicker/datetimepicker-theme.scss';

 @include mat.core();
```

**Comment by alexis-landrieu-avanade** [comment]
@bbortt I confirm it's working (you can see the build result [here](https://github.com/alexis-landrieu-avanade/mat-datetimepicker-sass-loader-issue-216/actions/runs/1676334059)), but it's a bit weird why we have to include node_modules in **stylePreprocessorOptions** ? Are you sure it's not your responsibility to export styles, refer to this documentation [ng-packagr - Copy assets - Exporting Styles](https://github.com/ng-packagr/ng-packagr/blob/master/docs/copy-assets.md#exporting-styles) ?

**Comment by bbortt** [comment]
it's a sass mixin, so I think we should. but I am not sure if `stylePreprocessorOptions` really is redundant after that.

**edit:** anyway, I will test it as soon as I find some time.. or feel free to open a PR 😉

**Comment by bbortt** [comment]
@alexis-landrieu-avanade I've added the `export` flag and that seems to work (tested it using your sample)! fix released in [`v9.0.22`](https://github.com/kuhnroyal/mat-datetimepicker/releases/tag/v9.0.22). thanks much for your help.

**Comment by alexis-landrieu-avanade** [comment]
I confirm it's working 🥇 , thank you for the update .

https://github.com/alexis-landrieu-avanade/mat-datetimepicker-sass-loader-issue-216/runs/4765901860?check_suite_focus=true

**Comment by JorgeAlcarazKuv** [comment]
@alexis-landrieu-avanade @bbortt Im still having this problem using the latest versions of Angular and @mat-datepicker. 
Did you manage to make this work without the stylePreprocessorOptions bit? Could you provide an example?

**Comment by bbortt** [comment]
I should be resolved as @alexis-landrieu-avanade showed in [the link provided](https://github.com/kuhnroyal/mat-datetimepicker/issues/216#issuecomment-1009240002).. please double check your settings.

**Comment by alexis-landrieu-avanade** [comment]
@bbortt I think the **Theming** part of the README.md file must be updated,

## Theming

```scss
@use '@mat-datetimepicker/core/datetimepicker/datetimepicker-theme' as matdp;

// Using the $theme variable from the pre-built theme you can call the theming function
@include matdp.mat-datetimepicker-theme($theme);
```

@JorgeAlcarazKuv  see [full example](https://github.com/alexis-landrieu-avanade/mat-datetimepicker-sass-loader-issue-216/blob/master/src/styles.scss#L4)

**Comment by bbortt** [comment]
that is probably true..
